### ISSUE TITLE
New error from using the function is_plugin_active_for_network()

### ISSUE THREAD

**Issue by isabelc** [webaware/disable-emails#1]
Version 1.6.0 has this error when viewing posts on the front end: 

`PHP Fatal error:  Uncaught Error: Call to undefined function webaware\disable_emails\is_plugin_active_for_network() in /var/www/html/wp-content/plugins/disable-emails/includes/functions.php:95`

An easy fix is shown in the [Example on this page](https://codex.wordpress.org/Function_Reference/is_plugin_active_for_network) in the WP Codex.

Excellent plugin, BTW.

**Comment by webaware** [comment]
Thanks Isabel, I'll get a fix out today!
