### ISSUE TITLE
Can't install on WP 5.5 or lower

### ISSUE THREAD

**Issue by jmslbam** [webaware/disable-emails#4]
A question, is this code so specific that it can only be installed on WP 5.5?

It's set here: https://github.com/webaware/disable-emails/blob/master/readme.txt#L8

**Comment by webaware** [comment]
Yes, the latest version will only work on WP 5.5 or later. PHPMailer has been updated, and using it the old way without namespace triggers deprecated warnings.

If you need to run this plugin on an older version of WordPress, please install version 1.6.3 which you can [download from the Advanced page for the plugin](https://wordpress.org/plugins/disable-emails/advanced/).

**Comment by jmslbam** [comment]
Thank you for the quick reply! I will download a previous version and try to upgrade WP as soon a possible on this project.

Kind regards Jaime!

P.s. Thank you for the plugin and all your work!
